### ISSUE TITLE
Sinister Seeds Piercing Damage

### ISSUE THREAD

**Issue by honkthebonk2** [Ygoproco/Live2017Links#1165]
The trap card "Sinister Seeds" can be activated if a monster you control that is in face-up defense position is killed by a monster that has piercing. The trap specifically calls for your monster being in Attack Position at the beginning of the damage step.

**Comment by NaimSantos** [comment]
A patch was uploaded for it in https://github.com/Ygoproco/Live2017Links/pull/1169. Should work for the scenario mentioned. This can be closed.
