### ISSUE TITLE
Invalid deck

### ISSUE THREAD

**Issue by DgZiga** [Ygoproco/Live2017Links#1233]
I have the following TCG decklist and it keeps getting an "Invalid Deck" popup when I try to select it in a match lobby.
This happens both with the correct banlist and when the banlist is set to "N/A"
(I had to zip the decklist file because of github)
![image](https://user-images.githubusercontent.com/16693505/45918587-84a4f400-be89-11e8-96cc-f84434562a2a.png)
[Kozmo.zip](https://github.com/Ygoproco/Live2017Links/files/2407902/Kozmo.zip)

**Comment by DgZiga** [comment]
Prankids are having this problem too.
Also, hosting a game with the "Dont check deck" option on is temprarily fixing this.
![image](https://user-images.githubusercontent.com/16693505/45919073-858d5400-be90-11e8-9189-31a2aae3686c.png)
[Prankids.zip](https://github.com/Ygoproco/Live2017Links/files/2407952/Prankids.zip)

**Comment by DgZiga** [comment]
When playing with the "Dont check deck" option on I noticed I only had 37 cards in both occasions.
When saving a replay and checking the deck, I found that both prankids rock and pot of indulgence were missing. Clearing the deck didnt work.

**Comment by ClementLouis** [comment]
Please Go on the Discord and read the pins or go check the forum for an explanation for that problem

**Comment by NaimSantos** [comment]
When reporting these, please keep them to [our Discord channel](discord.gg/ygopro-percy).  You will get an answer faster and there is no need to put this as an issue in our script repository. That's an issue with one of our servers and it is explained in the Discord channel.

**Comment by DgZiga** [comment]
Ok, thanks for the replies and I apologize for the trouble.
Seeing what looked like Issues mentions on the YGOPRo update I thought that this is where problems like these should be reported
Thanks again
