### ISSUE TITLE
banlist update

### ISSUE THREAD

**Issue by ghost** [Ygoproco/Live2017Links#1572]
could you update OCG , World, and Anime banlist to January 2019 banlist??

tnx

**Comment by ClementLouis** [comment]
It is the 3rd time I'm saying it (#681 and #1183 ) and I hope it is the last, the issue of the Github is **not** the place to ask that kind of stuff
You have the Forum (ygopro.co) and the Discord for that

and someone will work on the banlist when someone manage to free some time for it
