### ISSUE TITLE
Missing Counter in strings.conf

### ISSUE THREAD

**Issue by marikisthar** [Ygoproco/Live2017Links#167]
Scale Counter for Corrosive Scales is missing in strings.conf

the code for Scale Counter is 0x1045, and it's similar to RDA Archetype

**Comment by Ygoproco** [comment]
Thanks. Fixed in #171

**Comment by marikisthar** [comment]
also, could you fix misising [Rampaging Rhynos](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=6895) text, is semmse accidentally deleted from fixmisc,cdb

tnx
