### ISSUE TITLE
(New card scripts) Error in the old version of ygopro 2

### ISSUE THREAD

**Issue by egycno** [Ygoproco/Live2017Links#2444]
I put the new card scripts in the old version of ygopro 2 ,And I got this inside the game:

![2020-04-03_012527](https://user-images.githubusercontent.com/31624258/78385095-2a154980-7590-11ea-8ece-188cb260f1bc.png)
How do I fix it?
What files should I edit or replace?
I don't want to update the game because I have a bad internet connection

**Comment by NaimSantos** [comment]
This is a repository for Ygopro Percy 1.034. We do not provide support for Ygopro 2. Try to ask for help in their forum/discord/community
